### ISSUE TITLE
"Nie znaleziono pliku!"

### ISSUE THREAD

**Issue by mateuszgwozdz** [WMII-Informatyka-2017-2020/f-sprawdzarka#5]
taki error mi wyświetla `check.py` na sam koniec na czerwono. pewnie to nic ważnego, ale chciałem zwrócić uwagę xd

**Comment by hjaremko** [comment]
Prawdopodobnie chodzi o plik `input_custom.txt`, w którym można sobie zdefiniować własne testy.
